### DISCUSSION TITLE
Packagers: Notes for May 2025

### DISCUSSION THREAD

**Discussion by ReillyBrogan** [AerynOS/discussions#47] [General]
*** Ensure that Boulder and Boulder macros are fully updated, there are important macro and builddep changes that are required for things to keep building

- Package PRs *MUST* be based on the 2025-05-repo-rebuild branch *AND* be built against the infratest repo.
  - To do that you should modify your Boulder profiles to look something like this:
```
local-x86_64:
  repositories:
    volatile:
      uri: "https://dev.serpentos.com/volatile/x86_64/stone.index"
      description: "Volatile moss repo"
      priority: 0
    rebuild:
      uri: "https://infratest.aerynos.dev/vessel/volatile/x86_64/stone.index"
      description: "Rebuild repo"
      priority: 5
    local:
      uri: "file:///path/to/local/repo/stone.index"
      description: "Local development moss repo"
      priority: 10
```
- The cmake v4 update has likely broken the builds for a lot of cmake projects. Generally said projects just need to have their minimum cmake version increased, check the upstream repositories for commits or new versions with the fixes and backport the commits if necessary.
- `setuptools` has been split out of the `python` package and is now in `python-setuptools`. This should be pulled in automatically for builds that use `%python_setup` or `%python_install` but builds that use pyproject or other mechanisms to manage python code (like meson) may need `python(setuptools)` manually added as a builddep.
- The core parts of python have been split to a new `python-libs` package, while the `python`, `python3`, etc binaries are still in the `python` package. Generally `binary(python)` should only be used as a rundep for packages that ship executables (such as binaries in `/usr/bin`) that have a shebang requiring python. Other packages should depend on `python-libs` instead.
- Now that the vast majority of `toolchain: gnu` packages have been fixed to build against clang/llvm there is now a greater desire to keep the repo like that. Please ask for assistance in the packaging channel if you find any packages that seemingly require the GNU toolchain, there are almost always fixes that can be applied to make Clang work.
